FROM --platform=$TARGETPLATFORM alpine:3.10

ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETVARIANT

ENV OFFLINEIMAP_VERSION="7.2.4-r0" \
    CURL_VERSION="7.66.0-r3" \
    CA_CERTIFICATES_VERSION="20191127-r2" \
    PROCPS_VERSION="3.3.15-r0" \
    BASH_VERSION="5.0.0-r0"

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN apk add --no-cache \
      offlineimap="${OFFLINEIMAP_VERSION}" \
      ca-certificates="${CA_CERTIFICATES_VERSION}" \
      curl="${CURL_VERSION}" \
      procps="${PROCPS_VERSION}" \
      bash="${BASH_VERSION}" \
 && addgroup -S offlineimap \
 && adduser offlineimap -G offlineimap -D -H -h /workdir

ENV SUPERCRONIC_VERSION=v0.1.12
ENV SUPERCRONIC_URL="https://github.com/aptible/supercronic/releases/download/${SUPERCRONIC_VERSION}/supercronic-linux-${TARGETARCH}" \
    SUPERCRONIC="supercronic-linux-${TARGETARCH}" \
    SUPERCRONIC_SHA1SUM="SUPERCRONIC_SHA1SUM_${TARGETARCH}" \
    SUPERCRONIC_SHA1SUM_amd64="048b95b48b708983effb2e5c935a1ef8483d9e3e" \
    SUPERCRONIC_SHA1SUM_arm64="8baba3dd0b0b13552aca179f6ef10d55e5dee28b" \
    SUPERCRONIC_SHA1SUM_arm="d72d3d40065c0188b3f1a0e38fe6fecaa098aad5"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl -fsSLO "${SUPERCRONIC_URL}" \
 && echo "${!SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
 && chmod +x "${SUPERCRONIC}" \
 && mv "${SUPERCRONIC}" "/usr/local/bin/${SUPERCRONIC}" \
 && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

COPY crontab /etc/crontab

USER offlineimap

CMD /usr/local/bin/supercronic /etc/crontab

ARG CREATED
ARG REVISION=HEAD

LABEL org.opencontainers.image.authors="https://github.com/cewood" \
  org.opencontainers.image.created="${CREATED}" \ 
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.revision="${REVISION}" \
  org.opencontainers.image.source="https://github.com/cewood/offlineimap-docker/tree/${REVISION}" \
  org.opencontainers.image.title="cewood/offlineimap" \
  org.opencontainers.image.url="https://github.com/cewood/offlineimap-docker"
